# as of 3.11.2019 Github Actions just fires these release event actions: edited, published, released, deleted. Draft releases are missing created/unpublished
name: Deploy
on:
  release:
    types: [edited]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.type }} (${{ matrix.os }})
    strategy:
      matrix:
        type: [electron]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node: [12]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Build
        run: |
          npm install -g yarn
          yarn yarn:install
          yarn build:${{ matrix.type }}
      - name: Upload Release Artifacts
        uses: ./.github/actions/upload-release-asset
        with:
          glob_pattern: '**/Hyperion-Remote*[0-999].[0-999].[0-999]*'
          blacklist: 'blockmap'
          upload_url: ${{ github.event.release.upload_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-other:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.type }} (${{ matrix.os }})
    strategy:
      matrix:
        type: [spa, spaembed, pwa]
        os: [ubuntu-latest]
        node: [12]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Build
        run: |
          npm install -g yarn
          yarn yarn:install
          yarn build:${{ matrix.type }}
      - name: Upload Release Artifacts
        uses: ./.github/actions/upload-release-asset
        with:
          glob_pattern: '**/Hyperion-Remote*[0-999].[0-999].[0-999]*'
          blacklist: 'blockmap'
          upload_url: ${{ github.event.release.upload_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}