name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version of tag
        run: |
         echo ::set-env name=GH_TAG::${GITHUB_REF/refs\/tags\//}
         echo ::set-env name=CLEAN_VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
        # The github actions secret won't fire a release event for other workflows
        # https://github.com/actions/create-release/issues/52
          GITHUB_TOKEN: ${{ secrets.GHA_PSA }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Hyperion Remote ${{ env.CLEAN_VERSION }}
          body: Latest Release notes at [CHANGELOG.md](${{ github.event.repository.html_url}}/blob/master/CHANGELOG.md)
          draft: false
          prerelease: false
